config/routes.rb
UpdraftIo::Application.routes.draw do
  root 'home#index'
  post 'convert' => 'home#convert', :as => :convert

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :init_session_count

  def index
  end

  def convert
    render(status: 503) and return if session[:doc_count] > 10
    render(status: 500) and return unless params[:markdown]

    output = markdown.render(params[:markdown])
    response = create_pdf_in_docraptor(output)

    if response.code == 200
      session[:doc_count] += 1
      send_data response, filename: "updraft_output.pdf", type: 'pdf'
    else
      render inline: response.body, status: response.code
    end
  end

  private

  def init_session_count
    session[:doc_count] ||= 0
  end

  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end

  def create_pdf_in_docraptor(content)
    options = { 
      :test             => ! Rails.env.production?,
      :document_content => content
    }

    DocRaptor.create(options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.haml
%h1 updraft.io

%p.lede markdown &rarr; PDF

= form_tag convert_path, method: :post do
  
  = text_area_tag :markdown, "# markdown is neato"
  = submit_tag 'turn this markdown into a PDF now'


%footer
  %p made by <del><a href="http://supermatter.com">supermatter</a></del> <del><a href="http://refoundry.co">refoundry</a></del> <a href="http://tonydewan.com">Tony</a>

  %p.docraptor PDF creation by <br> <a href="http://docraptor.com/"><img src="http://docraptor.com/assets/docraptor-logo-60x43-96b1a35a179c453b27bfb996ec0854d7.png" /></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UpdraftIo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>